version: "3.8"

services:
  api:
    build: .
    container_name: api-container
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s

  tests:
    build: .
    container_name: test-container
    command: pytest
    network_mode: "service:api"  # Use API's network
    depends_on:
      api:
        condition: service_healthy